name: React VirtualTable component CI

on:
  release:
    types: [ created ]

jobs:
  publish-github-registry:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
    - run: yarn install
    - run: yarn build --if-present -- --env production
    - run: yarn test
    - run: yarn publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
